### ISSUE TITLE
refactor: Remove print statements from the code. 

### ISSUE THREAD

**Issue by ApheleiaS** [anitab-org/mentorship-ios#69]
**Describe the bug**
There are a lot of print statements in the code. Need to remove them and add logging instead. 

**To Reproduce**
Go to the following files
- mentorship ios/Models/LoginModel.swift 
- mentorship ios/Models/HomeModel.swift
- mentorship ios/Models/MemberModel.swift

**Comment by garima-bothra** [comment]
Hey. I would like to pick up this issue. Can you assign it to me?
(Just starting with opensource, feel free correct me if I'm going wrong somewhere)

**Comment by vatsalkul** [comment]
Hey @garima94921 Welcome to open source. Hope you will enjoy contributing to open source projects. 
I’ll assign this issue to you! If you want to get in touch with AnitaB.org open source organisation, I would suggest you to join us on zulip. http://anitab-org.zulipchat.com/
Enjoy Contributing 😊

**Comment by garima-bothra** [comment]
Thank you, looking forward to this new journey. I think this issue was meant for ViewModel and not Model files. Can you confirm?

**Comment by vatsalkul** [comment]
@garima94921 The code has updated since last 20 days. I think the main reason @ApheleiaS suggested to replace print with logging statements is that, it adds a timestamp and identifier to the output, whereas print will not.
What you can do for now is just remove print statement where it is irrelevant excluding print(token) in HomeViewModel file
If you face any problem, let us know😇
